language: node_js
node_js:
  - "stable"
notifications:
  email:
    on_success: always # only if status change from fail to success
    on_failure: always # if there is a fail
    recipients:
      - ps00552515@techmahindra.com
      - ub0034476@techmahindra.com
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: ./build
  on:
    branch: master